[package]
name = "pretty-name"
version = "1.0.0"
edition = "2024"
license = "MIT OR Apache-2.0"
keywords = ["name", "name-of", "name_of", "type-name", "type_name"]
categories = ["development-tools"]
repository = "https://github.com/NekomaruQwQ/pretty-name"
documentation = "https://docs.rs/pretty-name"
description = "Get the human-friendly name of types, functions, methods, fields, and enum variants in a refactoring-safe way."

[dependencies]
quote = "1.0"
prettyplease = "0.3.0"
syn = { version = "3.0.3", features = ["full", "visit-mut"] }

[dev-dependencies]
trybuild = "1.0.120"
